---
- name: Install Vim
  hosts: localhost
  become: yes  # Run tasks with sudo

  tasks:
    - name: Install Vim
      apt:
        name: vim
        state: present

- name: Install Git
  hosts: localhost
  become: yes  # Run tasks with sudo

  tasks:
    - name: Install Git
      apt:
        name: git
        state: present
      ignore_errors: yes

- name: Install Visual Studio Code
  hosts: localhost
  become: yes  # Run tasks with sudo

  tasks:
    - name: Add Microsoft GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present

    - name: Add Visual Studio Code repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present

    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Visual Studio Code
      apt:
        name: code
        state: present
